CREATE TABLE IF NOT EXISTS CABLES (
  ID NUMBER IDENTITY(1, 1) PRIMARY KEY,
  PRESET_ID NUMBER NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  CATEGORY VARCHAR(100),
  DIAMETER FLOAT NOT NULL,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FOREIGN KEY (PRESET_ID) REFERENCES PRESETS(ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS PRESETS (
  ID NUMBER IDENTITY(1, 1) PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE IF NOT EXISTS RESULTS (
  ID VARCHAR(12) PRIMARY KEY,
  INPUT_CABLES VARIANT NOT NULL,
  RESULT_DATA VARIANT NOT NULL,
  SELECTED_PRESET_ID NUMBER,
  CABLE_COUNT INT NOT NULL,
  BORE_DIAMETER FLOAT NOT NULL,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);