-- Seed data for presets and cables tables
-- This script populates the database with common real-world cable configurations

-- Insert Presets
INSERT INTO presets (name) VALUES 
  ('Residential Electrical'),
  ('Commercial Power'),
  ('Network Infrastructure'),
  ('Telecommunications'),
  ('Industrial Control');

-- Get preset IDs (these will be generated by SERIAL)
-- For PostgreSQL, we'll use the preset names to reference them

-- Residential Electrical Cables
INSERT INTO cables (preset_id, name, category, diameter) VALUES
  ((SELECT id FROM presets WHERE name = 'Residential Electrical'), '14 AWG Romex', 'Power', 0.31),
  ((SELECT id FROM presets WHERE name = 'Residential Electrical'), '12 AWG Romex', 'Power', 0.35),
  ((SELECT id FROM presets WHERE name = 'Residential Electrical'), '10 AWG Romex', 'Power', 0.43),
  ((SELECT id FROM presets WHERE name = 'Residential Electrical'), '6 AWG THHN', 'Power', 0.23),
  ((SELECT id FROM presets WHERE name = 'Residential Electrical'), 'Coaxial RG-6', 'Signal', 0.27),
  ((SELECT id FROM presets WHERE name = 'Residential Electrical'), 'Cat6 Ethernet', 'Data', 0.25),
  ((SELECT id FROM presets WHERE name = 'Residential Electrical'), 'Phone Line (22 AWG)', 'Telecom', 0.18);

-- Commercial Power Cables
INSERT INTO cables (preset_id, name, category, diameter) VALUES
  ((SELECT id FROM presets WHERE name = 'Commercial Power'), '4 AWG THHN', 'Power', 0.32),
  ((SELECT id FROM presets WHERE name = 'Commercial Power'), '2 AWG THHN', 'Power', 0.40),
  ((SELECT id FROM presets WHERE name = 'Commercial Power'), '1/0 AWG THHN', 'Power', 0.53),
  ((SELECT id FROM presets WHERE name = 'Commercial Power'), '2/0 AWG THHN', 'Power', 0.59),
  ((SELECT id FROM presets WHERE name = 'Commercial Power'), '3/0 AWG THHN', 'Power', 0.66),
  ((SELECT id FROM presets WHERE name = 'Commercial Power'), '4/0 AWG THHN', 'Power', 0.73),
  ((SELECT id FROM presets WHERE name = 'Commercial Power'), '250 MCM THHN', 'Power', 0.82),
  ((SELECT id FROM presets WHERE name = 'Commercial Power'), '350 MCM THHN', 'Power', 0.95);

-- Network Infrastructure Cables
INSERT INTO cables (preset_id, name, category, diameter) VALUES
  ((SELECT id FROM presets WHERE name = 'Network Infrastructure'), 'Cat5e Ethernet', 'Data', 0.24),
  ((SELECT id FROM presets WHERE name = 'Network Infrastructure'), 'Cat6 Ethernet', 'Data', 0.25),
  ((SELECT id FROM presets WHERE name = 'Network Infrastructure'), 'Cat6a Ethernet', 'Data', 0.35),
  ((SELECT id FROM presets WHERE name = 'Network Infrastructure'), 'Cat7 Ethernet', 'Data', 0.39),
  ((SELECT id FROM presets WHERE name = 'Network Infrastructure'), 'Single-mode Fiber (9/125)', 'Fiber', 0.12),
  ((SELECT id FROM presets WHERE name = 'Network Infrastructure'), 'Multi-mode Fiber (50/125)', 'Fiber', 0.12),
  ((SELECT id FROM presets WHERE name = 'Network Infrastructure'), 'Multi-mode Fiber (62.5/125)', 'Fiber', 0.12),
  ((SELECT id FROM presets WHERE name = 'Network Infrastructure'), 'Armored Fiber Cable', 'Fiber', 0.31);

-- Telecommunications Cables
INSERT INTO cables (preset_id, name, category, diameter) VALUES
  ((SELECT id FROM presets WHERE name = 'Telecommunications'), 'RG-6 Coaxial', 'Signal', 0.27),
  ((SELECT id FROM presets WHERE name = 'Telecommunications'), 'RG-11 Coaxial', 'Signal', 0.41),
  ((SELECT id FROM presets WHERE name = 'Telecommunications'), 'RG-59 Coaxial', 'Signal', 0.24),
  ((SELECT id FROM presets WHERE name = 'Telecommunications'), '25-Pair Telco Cable', 'Telecom', 0.47),
  ((SELECT id FROM presets WHERE name = 'Telecommunications'), '50-Pair Telco Cable', 'Telecom', 0.63),
  ((SELECT id FROM presets WHERE name = 'Telecommunications'), '100-Pair Telco Cable', 'Telecom', 0.89),
  ((SELECT id FROM presets WHERE name = 'Telecommunications'), 'Speaker Cable (16 AWG)', 'Audio', 0.19),
  ((SELECT id FROM presets WHERE name = 'Telecommunications'), 'Speaker Cable (12 AWG)', 'Audio', 0.27);

-- Industrial Control Cables
INSERT INTO cables (preset_id, name, category, diameter) VALUES
  ((SELECT id FROM presets WHERE name = 'Industrial Control'), '18 AWG Control Wire', 'Control', 0.15),
  ((SELECT id FROM presets WHERE name = 'Industrial Control'), '16 AWG Control Wire', 'Control', 0.17),
  ((SELECT id FROM presets WHERE name = 'Industrial Control'), '14 AWG Control Wire', 'Control', 0.20),
  ((SELECT id FROM presets WHERE name = 'Industrial Control'), 'Shielded Twisted Pair (18 AWG)', 'Control', 0.25),
  ((SELECT id FROM presets WHERE name = 'Industrial Control'), 'Motor Lead (12 AWG)', 'Power', 0.35),
  ((SELECT id FROM presets WHERE name = 'Industrial Control'), 'Motor Lead (10 AWG)', 'Power', 0.43),
  ((SELECT id FROM presets WHERE name = 'Industrial Control'), 'VFD Cable (14 AWG)', 'Power', 0.38),
  ((SELECT id FROM presets WHERE name = 'Industrial Control'), 'Instrumentation Cable', 'Signal', 0.22),
  ((SELECT id FROM presets WHERE name = 'Industrial Control'), 'Tray Cable (14 AWG)', 'Power', 0.42),
  ((SELECT id FROM presets WHERE name = 'Industrial Control'), 'Tray Cable (12 AWG)', 'Power', 0.48);

-- Summary of inserted data
-- 5 presets created:
--   1. Residential Electrical (7 cables)
--   2. Commercial Power (8 cables)
--   3. Network Infrastructure (8 cables)
--   4. Telecommunications (8 cables)
--   5. Industrial Control (10 cables)
-- Total: 41 cables

